name: Test Accessibility Checker

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run it manually

jobs:
  check-accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Accessibility Checker
        uses: berkeley-dsep-infra/jupyterlab-a11y-checker@fix/action-build-step
        with:
          files: "notebooks/**/*.ipynb"
